# Generated by Django 5.0.2 on 2024-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(default='shuw9tc', max_length=7),
        ),
    ]
