# Generated by Django 5.0.2 on 2024-02-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_otpverification_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=7),
        ),
    ]
