# Generated by Django 5.0.2 on 2024-05-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_otpverification_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_TOKEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
            ],
        ),
    ]
