# Generated by Django 5.0.2 on 2024-05-14 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_token',
            name='user',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
