# Generated by Django 5.0.2 on 2024-05-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_api_token_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_token',
            options={'verbose_name_plural': 'API KEYS'},
        ),
    ]
