# Generated by Django 5.0.2 on 2024-04-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos', '0001_initial'),
        ('perfil', '0002_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='friend_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amigos.friendlist'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='videos_calification',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
