# Generated by Django 5.0.2 on 2024-04-19 04:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfil_birth_day_perfil_friend_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='hide_information',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('name', 'name'), ('interested_cryptos', 'interested_cryptos'), ('description', 'description'), ('date_joined', 'date_joined'), ('friend_list', 'friend_list'), ('video_calification', 'video_calification')], default=list, max_length=200, null=True), null=True, size=None),
        ),
    ]
