# Generated by Django 5.0.2 on 2025-08-11 02:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_excludedrecomendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='hide_information',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('name', 'name'), ('interested_cryptos', 'interested_cryptos'), ('description', 'description'), ('date_joined', 'date_joined'), ('friend_list', 'friend_list'), ('videos_calification', 'videos_calification'), ('birth_day', 'birth_day')], max_length=200), blank=True, default=list, size=None),
        ),
    ]
