# Generated by Django 5.0.2 on 2024-06-04 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='user',
        ),
        migrations.AddField(
            model_name='preciobitcoin',
            name='simulacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.simulacion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='simulacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.simulacion'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='simulacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulador.simulacion'),
        ),
    ]
