# Generated by Django 5.0.2 on 2024-04-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_alert', '0002_alter_pricealertspecs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealertspecs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
