# Generated by Django 5.0.2 on 2024-03-14 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='attempts',
        ),
        migrations.AddField(
            model_name='quiz',
            name='change_status_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
