# Generated by Django 5.0.2 on 2024-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('news', models.CharField(max_length=300)),
                ('likes', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('views', models.IntegerField()),
                ('crypto', models.CharField(max_length=200)),
            ],
        ),
    ]
