# Generated by Django 5.0.2 on 2024-05-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_cryptostrending'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='date_fetched',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
