# Generated by Django 5.0.2 on 2024-05-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_date_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='compound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='date_fetched',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
