# Generated by Django 5.0.2 on 2024-04-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='criptomoneda_sold',
            field=models.CharField(max_length=201),
        ),
        migrations.AlterField(
            model_name='venta',
            name='criptomoneda_sold',
            field=models.CharField(max_length=201),
        ),
    ]
