# Generated by Django 5.0.2 on 2024-04-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_criptomoneda_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='criptomoneda_bought',
        ),
        migrations.AddField(
            model_name='venta',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra'),
        ),
    ]
