# Generated by Django 5.0.2 on 2024-05-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_venta_criptomoneda_bought_venta_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cuantity_bought',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cuantity_sold',
            field=models.FloatField(null=True),
        ),
    ]
