# Generated by Django 5.0.2 on 2024-05-27 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_cuantity_bought_venta_cuantity_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='compra',
        ),
        migrations.AddField(
            model_name='venta',
            name='criptomoneda_bought',
            field=models.CharField(max_length=201, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='max_percentage_lost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='venta',
            name='min_percentage_gain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
