# Generated by Django 5.0.2 on 2024-05-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_venta_compra_venta_criptomoneda_bought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='buying_price',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='selling_price',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
