# Generated by Django 5.0.2 on 2024-06-03 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_venta_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='max_percentage_lost',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='min_percentage_gain',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='max_percentage_lost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='min_percentage_gain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
