# Generated by Django 5.0.2 on 2025-07-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_compra_max_percentage_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra'),
        ),
    ]
